# Generated by Django 5.1.2 on 2024-10-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stall',
            name='description',
        ),
        migrations.AddField(
            model_name='activity',
            name='image_path',
            field=models.CharField(default='default_image.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='performance',
            name='image_path',
            field=models.CharField(default='default_image.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='stall',
            name='image_path',
            field=models.CharField(default='default_image.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performanceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stall',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='starreditem',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
