# Generated by Django 5.1.2 on 2024-10-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_activity_activityid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starreditem',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
